### ISSUE TITLE
Slider logo's worden afgekapt op mobiel + mogen iets kleiner

### ISSUE THREAD

**Issue by devbyray** [ShareValue-Frontend/frontend-landingpage#20]
<img width="445" alt="Screenshot 2022-11-04 at 15 52 51" src="https://user-images.githubusercontent.com/6241164/200005368-7ad38ad1-5129-4b1a-9a54-62125c33bcb9.png">

**Comment by marwanaboudaoud** [comment]
Inschatting: 3 uur
